### ISSUE TITLE
mogrify: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1391.

### ISSUE THREAD

**Issue by fofwisdom** [jankais3r/VitalSource-Grabber#1]
I have Helvetica font but process.sh printed error messages.
Advice please?
Thank you for making a wonderful scripts.

<img width="578" alt="Screen Shot 2020-02-27 at 12 41 52" src="https://user-images.githubusercontent.com/205521/75410252-97fd9e00-595e-11ea-96bb-59a60714a11e.png">
<img width="1119" alt="Screen Shot 2020-02-27 at 12 37 57" src="https://user-images.githubusercontent.com/205521/75410258-9f24ac00-595e-11ea-956b-b71a34ec015a.png">

**Comment by jankais3r** [comment]
Hi there, please try [this advice](https://apple.stackexchange.com/questions/224285/why-does-image-magick-fail-to-read-fonts). If it still doesn't work, let me know and we'll try other solutions.

**Comment by jankais3r** [comment]
Assuming the above advice solved the issue. Feel free to re-open if not.
