### ISSUE TITLE
401 unauthorised error while getting API key

### ISSUE THREAD

**Issue by girpa3** [jankais3r/VitalSource-Grabber#4]
Hey, I aam getting the secret key but not getting any response from print.vitalsource. Could not able to find API key.

**Comment by jankais3r** [comment]
This will not work without the API key.

**Comment by girpa3** [comment]
Have you figured out how to spoof ?
I might doing mistake so Please let us know it still works for you
Thanks for this wonderful project

**Comment by jankais3r** [comment]
As explained in readme, you can get both the API Key and the Access Token by inspecting VitalSource App's network traffic.

**Comment by girpa3** [comment]
I followed all steps you mentioned but did you check recently ? I guess vital-source made some changes in API. I could not get API now. It would be very helpful if you check again and let us know if there is something wrong I am doing

**Comment by jankais3r** [comment]
It's still there. The API keys are in the Header.
![api](https://user-images.githubusercontent.com/2159464/81174045-64b03e80-8fa1-11ea-9bd0-162f3f8d8086.png)

App version 9.0.0.1204

**Comment by girpa3** [comment]
Thank you so much. just wondering if it works for borrowed books?

**Comment by jankais3r** [comment]
If you can print a borrowed book in the app (I have no idea), the scripts can also download them. These two work exactly the same.

**Comment by jankais3r** [comment]
Closing this issue as I verified that the process still works, and no further feedback has been provided.
