### ISSUE TITLE
mitmproxy

### ISSUE THREAD

**Issue by ciroiriarte** [jankais3r/VitalSource-Grabber#7]
Hello, 

Did you need to do any special for the APP to recognize the new CA in order to extract the needed headers?. I'm trying with mitm on Windows, imported the CA in the system but the application fails to connect to the server for the print operations.

Might have it's own trusted CA list?

**Comment by jankais3r** [comment]
Unless they introduced certificate pinning into the app, there is no extra step needed. Are you able to intercept encrypted communication from all other apps with mitmproxy? If not, the CA cert is probablty not properly installed and trusted.

**Comment by ciroiriarte** [comment]
Web browser is passing through without warnings. Couldn't make it work, had to follow other route. :/
